language: python
matrix:
    include:
        - python: 3.8
          dist: bionic
          sudo: true
        - python: 3.8
          dist: bionic
          arch: arm64-graviton2
          sudo: true
install:
  - sudo apt-get install graphviz
  - pip install -r requirements.dev.txt
script:
  - tox
after_success:
  - coveralls
